title: whdzera
email: whdzera@gmail.com
description: >-
  Linktree whdzera
baseurl: ""
url: ""
blog: "https://whdzera.com"
username: "whdzera"
username_with_at: "@whdzera"
username_with_underscore: "_whdzera"
instagram: "@_whdzera"

include:
  - _app

exclude:
  - package.json
  - package-lock.json
  - README.md
  - Rakefile
  - vite.config.js
